$j(document).ready(function(){setupToggled();if($j('form#work-form')){hideFormFields();}
hideHideMe();showShowMe();handlePopUps();attachCharacterCounters();setupAccordion();setupDropdown();updateCachedTokens();$j('.splash').children('div:nth-of-type(odd)').addClass('odd');$j('.actions').children('.share').removeClass('hidden');$j('#inbox-form, .messages').find('.unreviewed').find('.review').find('a').removeClass('hidden');prepareDeleteLinks();thermometer();$j('body').addClass('javascript');});function get_token_input_options(self){return{searchingText:self.data('autocomplete-searching-text'),hintText:self.data('autocomplete-hint-text'),noResultsText:self.data('autocomplete-no-results-text'),minChars:self.data('autocomplete-min-chars'),queryParam:"term",preventDuplicates:true,tokenLimit:self.data('autocomplete-token-limit'),liveParams:self.data('autocomplete-live-params'),makeSortable:self.data('autocomplete-sortable')};}
var input=$j('input.autocomplete');if(input.livequery){jQuery(function($){$('input.autocomplete').livequery(function(){var self=$(this);var token_input_options=get_token_input_options(self);var method;try{method=$.parseJSON(self.data('autocomplete-method'));}catch(err){method=self.data('autocomplete-method');}
self.tokenInput(method,token_input_options);});});}
jQuery(function($){$('.expand').each(function(){list=$($(this).attr('action_target'));if(!list.attr('force_expand')||list.children().size()>25||list.attr('force_contract')){list.hide();$(this).show();}else{$(this).nextAll(".shuffle").show();$(this).next(".contract").show();}
$(this).click(function(event){list=$($(this).attr('action_target'));list.show();$(this).next(".contract").show();$(this).nextAll(".shuffle").show();$(this).hide();event.preventDefault();});});$('.contract').each(function(){$(this).click(function(event){list=$($(this).attr('action_target'));list.hide();$(this).prev(".expand").show();$(this).nextAll(".shuffle").hide();$(this).hide();event.preventDefault();});});$('.shuffle').each(function(){$(this).click(function(event){list=$($(this).attr('action_target'));list.children().shuffle();event.preventDefault();});});$('.expand_all').each(function(){target="."+$(this).attr('target_class');$(this).click(function(event){$(this).closest(target).find(".expand").click();event.preventDefault();});});$('.contract_all').each(function(){target="."+$(this).attr('target_class');$(this).click(function(event){$(this).closest(target).find(".contract").click();event.preventDefault();});});});jQuery(function($){$('.check_all').each(function(){$(this).click(function(event){var filter=$(this).data('checkbox-id-filter');var checkboxes;if(filter){checkboxes=$(this).closest('fieldset').find('input[id*="'+filter+'"][type="checkbox"]');}else{checkboxes=$(this).closest("fieldset").find(':checkbox');if(checkboxes.length==0){checkboxes=$(this).closest("fieldset").next().find(':checkbox');if(checkboxes.length==0){checkboxes=$(this).closest("fieldset").prev().find(':checkbox');}}}
checkboxes.prop('checked',true);event.preventDefault();});});$('.check_none').each(function(){$(this).click(function(event){var filter=$(this).data('checkbox-id-filter');var checkboxes;if(filter){checkboxes=$(this).closest('fieldset').find('input[id*="'+filter+'"][type="checkbox"]');}else{checkboxes=$(this).closest("fieldset").find(':checkbox');if(checkboxes.length==0){checkboxes=$(this).closest("fieldset").next().find(':checkbox');if(checkboxes.length==0){checkboxes=$(this).closest("fieldset").prev().find(':checkbox');}}}
checkboxes.prop('checked',false);event.preventDefault();});});});function setupToggled(){$j('.toggled').filter(function(){return $j(this).closest('.userstuff').length===0;}).each(function(){var node=$j(this);var open_toggles=$j('.'+node.attr('id')+"_open");var close_toggles=$j('.'+node.attr('id')+"_close");if(node.hasClass('open')){close_toggles.each(function(){$j(this).show();});open_toggles.each(function(){$j(this).hide();});}else{node.hide();close_toggles.each(function(){$j(this).hide();});open_toggles.each(function(){$j(this).show();});}
open_toggles.each(function(){$j(this).click(function(e){if($j(this).attr('href')=='#'){e.preventDefault();}
node.show();open_toggles.each(function(){$j(this).hide();});close_toggles.each(function(){$j(this).show();});});});close_toggles.each(function(){$j(this).click(function(e){if($j(this).attr('href')=='#'){e.preventDefault();}
node.hide();close_toggles.each(function(){$j(this).hide();});open_toggles.each(function(){$j(this).show();});});});});}
function hideHideMe(){$j('.hideme').each(function(){$j(this).hide();});}
function showShowMe(){$j('.showme').each(function(){$j(this).show();});}
function handlePopUps(){$j("a[data_popup]").click(function(event,element){if(event.stopped)return;window.open($j(element).attr('href'));event.stop();});}
function remove_section(link,class_of_section_to_remove){$j(link).siblings(":input[type=hidden]").val("1");var section=$j(link).closest("."+class_of_section_to_remove);section.find(".required input, .required textarea").each(function(index){var element=eval('validation_for_'+$j(this).attr('id'));element.disable();});section.hide();}
function add_section(link,nested_model_name,content){var last_id=parseInt($j(link).parent().siblings('.last_id').last().html());var new_id=last_id+1;var regexp=new RegExp("new_"+nested_model_name,"g");content=content.replace(regexp,new_id);content=content.replace('class="hidden showme"','');$j(link).parent().before(content);}
function toggleFormField(element_id){var ticky=$j('#'+element_id+'-show');if(ticky.is(':checked')){$j('#'+element_id).removeClass('hidden');}
else{$j('#'+element_id).addClass('hidden');if(element_id!='chapters-options'&&element_id!='backdate-options'){$j('#'+element_id).find(':input[type!="hidden"]').each(function(index,d){if($j(d).attr('type')=="checkbox"){$j(d).attr('checked',false);}
else{$j(d).val('');}});}}
if(element_id=='chapters-options'){var item=document.getElementById('work_wip_length');if(item.value==1||item.value=='1'){item.value='?';}
else{item.value=1;}}}
function hideFormFields(){if($j('form#work-form')!=null){var toHide=['#co-authors-options','#front-notes-options','#end-notes-options','#chapters-options','#parent-options','#series-options','#backdate-options','#override_tags-options'];$j.each(toHide,function(index,name){if($j(name)){if(!($j(name+'-show').is(':checked'))){$j(name).addClass('hidden');}}});$j('form#work-form').className=$j('form#work-form').className;}}
function hideField(id){$j('#'+id).toggle();}
function attachCharacterCounters(){var countFn=function(){var counter=(function(input){var cc=$j('.character_counter [id='+input.attr('id')+'_counter]');if(cc.length===1){return cc;}
cc=input.nextAll('.character_counter').first().find('.value');if(cc.length){return cc;}
var parent=input.parent();for(var i=0;i<2;i++){cc=parent.nextAll('.character_counter').find('.value');if(cc.length){return cc;}
parent=parent.parent();}
return $j();})($j(this)),max=parseInt(counter.attr('data-maxlength'),10),val=$j(this).val().replace(/\r\n/g,'\n').replace(/\r|\n/g,'\r\n'),remaining=max-val.length;counter.html(remaining).attr("aria-valuenow",remaining);};$j(document).on('keyup keydown mouseup mousedown change','.observe_textlength',countFn);$j('.observe_textlength').each(countFn);}
function setupDropdown(){$j('#header').find('.dropdown').attr("aria-haspopup",true);$j('#header').find('.dropdown, .dropdown .actions').children('a').attr({'class':'dropdown-toggle','data-toggle':'dropdown','data-target':'#'});$j('.dropdown').find('.menu').addClass("dropdown-menu");}
function setupAccordion(){$j(".expandable").filter(function(){return $j(this).closest(".userstuff").length===0;}).each(function(){var pane=$j(this);if(!pane.hasClass("hidden")){pane.addClass("hidden");};pane.prev().removeClass("hidden").addClass("collapsed").click(function(e){var expander=$j(this);if(expander.attr('href')=='#'){e.preventDefault();};expander.toggleClass("collapsed").toggleClass("expanded").next().toggleClass("hidden");});});}
function prepareDeleteLinks(){$j('a[href$="/confirm_delete"][data-confirm]').each(function(){this.href=this.href.replace(/\/confirm_delete$/,"");$j(this).attr("data-method","delete");});$j('a[href$="/confirm_purge"][data-confirm]').each(function(){this.href=this.href.replace(/\/confirm_purge$/,"/purge");$j(this).attr("data-method","post");});}
$j(document).ready(function(){$j('input#kudo_submit').on("click",function(event){event.preventDefault();$j.ajax({type:'POST',url:'/kudos.js',data:jQuery('#new_kudo').serialize(),error:function(jqXHR,textStatus,errorThrown){var msg='Sorry, we were unable to save your kudos';if(jqXHR.status=="429"){msg="Sorry, you can't leave more kudos right now. Please try again in a few minutes.";}else{var data=$j.parseJSON(jqXHR.responseText);if(data.error_message){msg=data.error_message;}}
$j('#kudos_message').addClass('kudos_error').text(msg);},success:function(data){$j('#kudos_message').addClass('notice').text('Thank you for leaving kudos!');}});});$j('#comments_placeholder').on('click.rails','.pagination a[data-remote]',function(e){$j.scrollTo('#comments_placeholder');});$j("#show_comments_link_top").on('click.rails','a[href*="show_comments"]',function(e){$j.scrollTo('#comments');});});$j(document).ready(function(){$j('form.ajax-create-destroy').on("click",function(event){event.preventDefault();var form=$j(this);var formAction=form.attr('action');var formSubmit=form.find('[type="submit"]');var createValue=form.data('create-value');var destroyValue=form.data('destroy-value');var flashContainer=$j('.flash');$j.ajax({type:'POST',url:formAction,data:form.serialize(),dataType:'json',success:function(data){flashContainer.removeClass('error').empty();if(data.item_id){flashContainer.addClass('notice').html(data.item_success_message);formSubmit.val(destroyValue);form.append('<input name="_method" type="hidden" value="delete">');form.attr('action',formAction+'/'+data.item_id);}else{flashContainer.addClass('notice').html(data.item_success_message);formSubmit.val(createValue);form.find('input[name="_method"]').remove();form.attr('action',formAction.replace(/\/\d+/,''));}},error:function(xhr,textStatus,errorThrown){flashContainer.empty();flashContainer.addClass('error notice');try{jQuery.parseJSON(xhr.responseText);}catch(e){flashContainer.append("We're sorry! Something went wrong.");return;}
$j.each(jQuery.parseJSON(xhr.responseText).errors,function(index,error){flashContainer.append(error+" ");});}});});});$j(document).ready(function(){$j('form.ajax-remove').on("click",function(event){event.preventDefault();var form=$j(this);var formAction=form.attr('action');if(form.closest('li.group').length!==0){formParent=form.closest('li.group');}else{formParent=form.closest('tr');};var parentContainer=formParent.closest('div:not(.admin)');var flashContainer=parentContainer.find('.flash');$j.ajax({type:'POST',url:formAction,data:form.serialize(),dataType:'json',success:function(data){flashContainer.removeClass('error').empty();flashContainer.addClass('notice').html(data.item_success_message);},error:function(xhr,textStatus,errorThrown){flashContainer.empty();flashContainer.addClass('error notice');try{jQuery.parseJSON(xhr.responseText);}catch(e){flashContainer.append("We're sorry! Something went wrong.");return;}
$j.each(jQuery.parseJSON(xhr.responseText).errors,function(index,error){flashContainer.append(error+" ");});}});$j(document).ajaxSuccess(function(){formParent.slideUp(function(){$j(this).remove();});});});});function thermometer(){var banners=$j('.announcement').filter(function(){return $j(this).closest('.userstuff').length===0;});banners.has('.goal').each(function(){var banner_content=$j(this).find('blockquote');banner_goal_text=banner_content.find('span.goal').html();banner_progress_text=banner_content.find('span.progress').html();if($j(this).find('span.goal').hasClass('stretch')){stretch=true}else{stretch=false}
goal_amount=parseFloat(banner_goal_text.replace(/\.(?![0-9])|[^\.0-9]/g,''));progress_amount=parseFloat(banner_progress_text.replace(/\.(?![0-9])|[^\.0-9]/g,''));percentage_amount=Math.min(Math.round(progress_amount/goal_amount*1000)/10,100);banner_content.append('<div class="thermometer-content"><div class="thermometer"><div class="track"><div class="goal"><span class="amount">'+banner_goal_text+'</span></div><div class="progress"><span class="amount">'+banner_progress_text+'</span></div></div></div></div>');if(stretch==true){banner_content.find('div.track').css({'background':'#8eb92a','background-image':'linear-gradient(to bottom, #bfd255 0%, #8eb92a 50%, #72aa00 51%, #9ecb2d 100%)'});banner_content.find('div.progress').css({'width':percentage_amount+'%','background':'#4d7c10','background-image':'linear-gradient(to bottom, #6e992f 0%, #4d7c10 50%, #3b7000 51%, #5d8e13 100%)'});}else if(percentage_amount>=100){banner_content.find('div.progress').css({'width':'100%','background':'#8eb92a','background-image':'linear-gradient(to bottom, #bfd255 0%, #8eb92a 50%, #72aa00 51%, #9ecb2d 100%)'});}else if(percentage_amount>=85){banner_content.find('div.progress').css({'width':percentage_amount+'%','background':'#d2e638','background-image':'linear-gradient(to bottom, #e6f0a3 0%, #d2e638 50%, #c3d825 51%, #dbf043 100%)'});}else if(percentage_amount>=30){banner_content.find('div.progress').css({'width':percentage_amount+'%','background':'#fccd4d','background-image':'linear-gradient(to bottom, #fceabb 0%, #fccd4d 50%, #f8b500 51%, #fbdf93 100%)'});}else{banner_content.find('div.progress').css({'width':percentage_amount+'%','background':'#f17432','background-image':'linear-gradient(to bottom, #feccb1 0%, #f17432 50%, #ea5507 51%, #fb955e 100%)'});}});}
function updateCachedTokens(){if($j('#small_login').length>0){$j.getJSON("/token_dispenser.json",function(data){var token=data.token;$j('input[name=authenticity_token]').each(function(){$j(this).attr('value',token);});$j('meta[name=csrf-token]').attr('content',token);$j.event.trigger({type:"loadedCSRF"});});}else{$j.event.trigger({type:"loadedCSRF"});}}